### PR TITLE
add implicit codec to handle java.nio.charset.MalformedInputException

### PR DESCRIPTION
**Pull request by dgouyette**
```
"scala.io.BufferedSource.mkString(BufferedSource.scala:96)",
    "com.gilt.handlebars.scala.partial.PartialHelper$.findAllPartials(PartialHelper.scala:51)",
    "com.gilt.handlebars.scala.partial.PartialHelper$.getTemplates(PartialHelper.scala:67)",
    "com.gilt.handlebars.scala.DefaultHandlebarsBuilder$.apply(HandlebarsBuilder.scala:40)",
    "com.gilt.handlebars.scala.Handlebars$.createBuilder(Handlebars.scala:48)",
  ```

see http://stackoverflow.com/questions/13625024/how-to-read-a-text-file-with-mixed-encodings-in-scala-or-java

### CODE REVIEW

**Comment by timcharper** [comment]
Hmm, it seems like maybe this should be parameterized.

**Comment by dgouyette** [comment]
Ok I'll update my pull request 😏

**Comment by dgouyette** [comment]
Pull request updated

**Comment by timcharper** [comment]
Perfect! A default implicit `Codec` is provided by Scala so source compatibility should be retained.

**Pull request merged**
